spring:
  r2dbc:
    url: r2dbc:mssql://db.xy.com:1433/eProjectFileTable
    username: dev
    password: dev123
    name: eProjectFileTable

eproject:
  filetable:
    share:
      path: \\WIN-P7IGB7G8JV6\MSSQLSERVER2012FS\eProjectFileTable_fs_dir